### ISSUE TITLE
Output Format Confuzzled

### ISSUE THREAD

**Issue by InfernalSeraph** [tjradj/Gamebryo-Engine-Unit-Converter#1]
```
C:\[redacted]>ck-unit-conv u 512 f
        ←[38;5;10m512.000000←[0m u      =  ←[38;5;10m24.000000←[0m '
```
```
C:\[redacted]>conv u 512 f
        512.000000 u    =  24.000000 '
```

Output 1 is from 4.2.0 without any config. I realize now that it's the color codes being messed up somehow and it works once there's an INI with `disable-colors = true`.

Output 2 is from 4.1.0 without any config. Color is present.

Running on Microsoft Windows version 10.0.19042.1165 in CMD, not sure if that affects anything.
Same output in PowerShell, though I should point out that the medium green output has minimal contrast with the medium blue of the default PowerShell console.

**Comment by radj307** [comment]
The issue arises from how windows handles ANSI escape sequences, which it doesn't unless explicitly enabled.

I updated to using them as windows has basic support for them now, but clearly `ENABLE_VIRTUAL_TERMINAL_PROCESSING` isn't being set correctly.

I'll add an INI setting to enable ANSI color support as an optional feature, and use the Win32 API's colors by default.

**Comment by radj307** [comment]
Should be fixed as of [v4.2.1](https://github.com/radj307/Gamebryo-Engine-Unit-Converter/releases/tag/v4.2.1)

**Comment by InfernalSeraph** [comment]
With the same command prompt still open and just swapping in the new 4.2.1 executable, I can confirm the output is formatted properly.
Thank you!

**Comment by InfernalSeraph** [comment]
On another machine, I downloaded the current release (5.0.4) and was getting those unhandled ANSI escape sequences again.

I came across this [forum post](https://www.dostips.com/forum/viewtopic.php?t=9144) which mentioned that the Windows 10 console has support for ANSI sequences, but 
> the program writing to the console must configure its output to interpret the sequences.

The poster also mentioned that there's a registry key that can reverse the opt-in nature of support [for ANSI sequences] and, after trying it, I can confirm it works fine. I don't think that workaround would be a good recommendation for Windows users however, as modifying the Registry is generally discouraged.

I should also mention that the ini file doesn't seem to be read (I set the no-color flag to true while testing).

**Comment by radj307** [comment]
Sorry for the trouble; this should have been properly resolved by now.  
I'm going to migrate the project to use a more robust version of `TermAPI`, which should permanently resolve this.

**Comment by radj307** [comment]
Try using this:  
https://github.com/radj307/ckconv/releases/tag/6.0.0  
You can pass the `-qn` options to optimize the output for shell scripts.  
Let me know if that resolves the problem for you.

**Comment by InfernalSeraph** [comment]
To test, I reversed the registry edit I had used based on the forum post I linked earlier. Then I retried running the old version just to confirm the registry change was applied. This showed the raw codes like follows:
`C:\var\tools> ckconv 200 u ft`
`←[38;5;2m200←[39m←[49m←[22m←[24m←[27m ←[38;5;7m←[1mu←[39m←[49m←[22m←[24m←[27m`   `←[38;5;7m=←[39m←[49m←[22m←[24m←[27m ←[38;5;2m9.375←[39m←[49m←[22m←[24m←[27m` `←[38;5;7m←[1m'←[39m←[49m←[22m←[24m←[27m`

Then I downloaded the release you linked above and put it in the exact same location and named it ckconv-6 for testing.
Output was immediately as expected without needing to reactivate the registry edit or anything else.
`C:\var\tools> ckconv-6 200 u ft`
`200 u = 9.375 '`
The 200 was light blue and the 9.375 was green.

-n works as usual. -q removes the source figure, outputting just the result. It's a nice touch that arguments can be stacked.
